Feature2
akiho-o/customers pull request #2
Opened 2021-06-24 12:31 UTC by akiho-o

こっちでした！！

2021-06-24 13:14 UTC, yukishimizumg commented
@akiho-o 
変更内容がない場合のバリデーションについて、タスク管理アプリのほうが参考になると思います✨
https://github.com/elites-team/23rd-century-4th/blob/master/doc/06_php/study02/04_task/07.md

```php
// タスク更新時のバリデーション
function updateValidate($title, $task)
{
    $errors = [];

    if ($title == '') {
        $errors[] = MSG_TITLE_REQUIRED;
    }

    if ($title == $task['title']) {
        $errors[] = MSG_TITLE_NO_CHANGE;
    }

    return $errors;
}
```

1個以上と書いてくれてますが、入力内容がすべて変更されていない場合にエラーメッセージ表示でOKです！
少し考えてみてわからなければまた聞いてください✨😊

2021-06-24 20:58 UTC, kazu-taka requested changes
@akiho-o 
コメントしたので確認お願いします:bow:

2021-06-24 20:58 UTC, kazu-taka commented on new.php
> +}
@akiho-o 
インデントがずれているので、修正お願いします:bow:
```php
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // フォームに入力されたデータの受け取り
    $company = filter_input(INPUT_POST, 'company');
    $name = filter_input(INPUT_POST, 'name');
    $email = filter_input(INPUT_POST, 'email');

    // バリデーション
    $errors_required = validateRequired($company, $name, $email);

    // エラーメッセージの配列をマージ
    $errors = array_merge($errors_required);

    if (empty($errors)) {
        insertBt($company, $name, $email);

        header('Location: index.php');
        exit;
    }
}
```

2021-06-24 20:58 UTC, kazu-taka commented on functions.php
> +function insertBt($company, $name, $email)
@akiho-o 
insertBtやupdateBtのBtというのは、体温の略なので、insertCustomerやupdateCustomerに修正して下さい🙏

2021-06-24 20:58 UTC, kazu-taka commented on functions.php
> +
@akiho-o 
何も変更されていない条件は、「会社名と名前とメールアドレス」の全てが変更されていない時にメッセージを出すので、個別にチェックするのではなく、一緒に1つのif文で確認する必要があります✨

2021-06-27 07:52 UTC, yukishimizumg commented on new.php
> +}
@akiho-o 
修正が漏れているようなので、対応お願いします✨

2021-06-27 08:18 UTC, kazu-taka commented
@akiho-o 
マージしてOKです！！
お疲れさまでした✨
![LGTM](https://image.lgtmoon.dev/131777)

2021-06-27 13:27 UTC, merged